---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: transaction-service
  name: transaction-service-placement-1-vault
  namespace: bank-infra
spec:
  clusterSelector:
    matchLabels:
      'cluster.open-cluster-management.io/clusterset': 'azure-aws-clusterset'
