apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-simulator-deployment-vault
  labels:
    app: mobile-simulator
spec:
  selector:
    matchLabels:
      app: mobile-simulator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mobile-simulator
    spec:
      containers:
        - image: quay.io/wdovey/mobile-simulator:css-fix
          imagePullPolicy: Always
          name: mobile-simulator-vault
          envFrom:
            - secretRef:
                name: mobile-simulator-secrets-vault
          env:
            - name: PORT-vault
              value: '8080'
          ports:
            - containerPort: 8080
