---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: mobile-simulator-secrets
  namespace: bank-infra
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secretstore-vault
    kind: ClusterSecretStore
  target:
    name: mobile-simulator-secrets
  data:
  - secretKey: APP_ID_CLIENT_ID
    remoteRef:
      key: example-bank/app_id_infra
      property: APP_ID_CLIENT_ID
  - secretKey: APP_ID_CLIENT_SECRET
    remoteRef:
      key: example-bank/app_id_infra
      property: APP_ID_CLIENT_SECRET
  - secretKey: APP_ID_IAM_APIKEY
    remoteRef:
      key: example-bank/app_id_infra
      property: APP_ID_IAM_APIKEY
  - secretKey: APP_ID_MANAGEMENT_URL
    remoteRef:
      key: example-bank/app_id_infra
      property: APP_ID_MANAGEMENT_URL
  - secretKey: APP_ID_TOKEN_URL
    remoteRef:
      key: example-bank/app_id_infra
      property: APP_ID_TOKEN_URL
  - secretKey: PROXY_TRANSACTION_MICROSERVICE
    remoteRef:
      key: example-bank/app_id_infra
      property: PROXY_TRANSACTION_MICROSERVICE
  - secretKey: PROXY_USER_MICROSERVICE
    remoteRef:
      key: example-bank/app_id_infra
      property: PROXY_USER_MICROSERVICE